version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
